django/hello_world/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
]

django/internship_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('work_system.urls')),
    path('hello_world/', include('hello_world.urls')),
    path('admin/', admin.site.urls),
]

django/work_system/urls.py
from django.urls import path
from . import views

app_name = 'work_system'
urlpatterns = [
    path('', views.home, name='home'),
    path('index.html', views.home, name='home'),
    path('task/<int:task_id>/detail', views.task_detail, name='task_detail'),
    path('login/email', views.email_login, name='email_login'),
    path('login/email/<str:token>', views.email_login_token, name='email_login_token'),
    path('login/email_sent/<str:email>', views.email_sent, name='email_sent'),
    path('logout', views.logout, name='logout'),
    path('account_created', views.account_created, name='account_created'),
    path('create_task', views.create_task, name='create_task'),
    path('create_task/succses', views.create_task_success, name='create_task_success'),
    path('no_permission', views.no_permission, name='no_permission'),
    path('reserve_task/<int:task_id>', views.reserve_task, name='reserve_task'),
    path('task_reserved', views.task_reserved, name='task_reserved'),
    path('task_full', views.task_full, name='task_full'),
]

django/hello_world/models.py
from django.db import models

# Create your models here.

django/work_system/models.py
from django.db import models
from django import forms
from django.contrib.auth import models as auth_model
from django.utils.timezone import now


# Create your models here.
class User(auth_model.AbstractUser):
    isEmployee = models.BooleanField(default=False)
    pass


class Task(models.Model):
    title = models.CharField(max_length=100)
    value = models.IntegerField()
    timeEstimation = models.DurationField()
    employer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    worker = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_query_name='taskTodo')
    description = models.TextField()
    dateCreated = models.DateTimeField(default=now)

    class Meta:
        ordering = ["dateCreated"]
        permissions = [('can_create_task', 'can create task'), ('can_reserve_task', 'can reserve task')]
        pass

    pass


class EmailToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=64, unique=True)


class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    password_rpt = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'isEmployee']
        pass

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("password_rpt")

        if password != confirm_password:
            raise forms.ValidationError('password and confirm_password does not match')
        pass

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("This email already used")
        return data

    pass


class TaskForm(forms.ModelForm):
    timeEstimationDay = forms.IntegerField(min_value=0)
    timeEstimationHour = forms.IntegerField(min_value=0, max_value=23)

    class Meta:
        model = Task
        fields = ['title', 'value', 'description']
        pass

    def clean(self):
        cleaned_data = super(TaskForm, self).clean()
        day = cleaned_data.get("timeEstimationDay", 0)
        value = cleaned_data.get("value", 0)
        if day <= 3 and value > 30000:
            raise forms.ValidationError('حداکثر قیمت کار‌های با زمان ۳ روز ۳۰۰۰۰ تومان می باشد')
        pass

    def clean_value(self):
        data = self.cleaned_data['value']
        if data < 1000 or data > 50000:
            raise forms.ValidationError("قیمت باید بین ۱۰۰۰ تا ۵۰۰۰۰ تومان باشد")
        return data

django/hello_world/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.

def home(request):
    return HttpResponse("سلام!!!")

django/work_system/views.py
import secrets
from datetime import timedelta

import redis
from django import shortcuts
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.mail import send_mail
from django.core.paginator import Paginator

from . import models

redis_connection = redis.Redis(port=settings.REDIS_PORT, decode_responses=True)


# Create your views here.
def home(request):
    task_list = models.Task.objects.all()
    paginator = Paginator(task_list, 2)
    form = models.SignupForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save()
            print(user.isEmployee)
            if user.isEmployee:
                content_type = ContentType.objects.get_for_model(models.Task)
                permission = Permission.objects.get(codename='can_create_task', content_type=content_type)
            else:
                content_type = ContentType.objects.get_for_model(models.Task)
                permission = Permission.objects.get(codename='can_reserve_task', content_type=content_type)
            user.user_permissions.add(permission)
            return shortcuts.redirect('work_system:account_created')
    if 'page' in request.GET:
        page_number = request.GET.get('page')
        request.session['page'] = page_number
    elif 'page' in request.session:
        page_number = request.session['page']
    else:
        page_number = 1
    page_obj = paginator.get_page(page_number)
    return shortcuts.render(request, 'index.html', {'page_obj': page_obj, 'signup_form': form})


def account_created(request):
    return shortcuts.render(request, 'account_created.html')


def task_detail(request, task_id):
    task = shortcuts.get_object_or_404(models.Task, pk=task_id)
    return shortcuts.render(request, 'details.html', {'task': task})


def email_login(request):
    token = secrets.token_urlsafe(32)
    email: str = request.POST['email']
    user = shortcuts.get_object_or_404(models.User, email=email.lower())
    redis_connection.set(token, user.username, ex=3600)
    send_mail(
        subject='login',
        message='goto this link\n' +
                request.build_absolute_uri(shortcuts.reverse('work_system:email_login_token', args=(token,))),
        from_email=None,
        recipient_list=[email],
    )
    return shortcuts.redirect('work_system:email_sent', email)


def email_login_token(request, token):
    username = redis_connection.get(token)
    if username is None:
        return shortcuts.Http404()
    redis_connection.delete(token)
    auth.login(request, shortcuts.get_object_or_404(models.User, username=username))
    return shortcuts.redirect('work_system:home')


def email_sent(request, email):
    return shortcuts.render(request, 'send_mail.html', {'email': email})


def logout(request):
    auth.logout(request)
    return shortcuts.redirect('work_system:home')


@permission_required('work_system.can_create_task', login_url='/no_permission')
def create_task(request):
    form = models.TaskForm(request.POST or None)
    if form.is_valid():
        task = form.save(commit=False)
        task.employer = request.user
        task.timeEstimation = timedelta(form.cleaned_data['timeEstimationDay'], form.cleaned_data['timeEstimationHour'])
        task.save()
        return shortcuts.redirect('work_system:create_task_success')
    return shortcuts.render(request, 'new_task.html', {'form': form})


def create_task_success(request):
    return shortcuts.render(request, 'task_created.html')


def no_permission(request):
    return shortcuts.render(request, 'no_permission.html')


@permission_required('work_system.can_reserve_task', login_url='/no_permission')
def reserve_task(request, task_id):
    task = shortcuts.get_object_or_404(models.Task, pk=task_id)
    if not task.worker:
        task.worker = request.user
        task.save()
        return shortcuts.redirect('work_system:task_reserved')
    else:
        return shortcuts.redirect('work_system:task_full')
    pass


def task_reserved(request):
    return shortcuts.render(request, 'task_reserved.html')


def task_full(request):
    return shortcuts.render(request, 'task_full.html')

django/work_system/templates/account_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>message</title>
</head>
<body>
<div style="
width: 100%;
text-align: center;
padding-top: 200px;
font-size: large;
"
dir="rtl">
    حساب کاربری شما با موفقیت ساخته شد به صفحه‌ی اصلی رفته و لاگین کنید.
</div>
<div style="
width: 100%;
padding-top: 15px;
text-align: center;
font-size: large;
"
dir="rtl">
    <a href="{% url 'work_system:home' %}">
        صفحه‌ی اصلی
    </a>
</div>
</body>
</html>

django/work_system/templates/details.html
<!DOCTYPE html>
<html lang="fa">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'work_system/main.css' %}">
    {#    <link rel="stylesheet" href="../static/work_system/main.css">#}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>detail</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div id="main-content" class="col-md-9">
            <h1> سامانه‌ی انجام کار</h1>
            <div>
                <div class="col-sm-12">
                    {% if not user.isEmployee %}
                        <form action="{% url 'work_system:reserve_task' task.pk %}" method="get">
                            {% csrf_token %}
                            <h3 style="display: inline-block">{{ task.title }}</h3>
                            <button type="submit" class="btn btn-default">انجام می‌دم</button>
                        </form>
                    {% endif %}
                    <a class=""></a>
                    <hr/>
                </div>
                <div class="col-sm-2"></div>
                <div class="col-sm-4">ساخته شده در {{ task.dateCreated }}</div>
                <div class="col-sm-3">{{ task.value }} تومان</div>
                <div class="col-sm-3">{{ task.timeEstimation }}</div>
                <div class="col-sm-12">
                    <br/>
                    توضیحات:
                    <br/>
                    {{ task.description }}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            {% if user.is_authenticated %}
                <h5> شما با نام کاربری {{ user.get_username }} وارد شده‌اید. </h5>
                <a class="btn btn-default btn-block" href="{% url 'work_system:home' %}">صفحه‌ی اصلی</a>
                <a class="btn btn-default btn-block" href="{% url 'work_system:logout' %}">خروج</a>
            {% else %}
                <a class="btn btn-default btn-block" href="{% url 'work_system:home' %}">صفحه‌ی اصلی</a>
            {% endif %}
        </div>
    </div>
    <footer>
        <hr/>
        <span>درباه‌ی ما</span>
        <span>قوانین</span>
    </footer>
</div>
</body>
</html>

django/work_system/templates/index.html
<!DOCTYPE html>
<html lang="fa">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    {% load static %}
    <link rel="stylesheet" href="{% static 'work_system/main.css' %}">
    {#    <link rel="stylesheet" href="../static/work_system/main.css">#}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>index</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div id="main-content" class="col-md-9">
            <h1> سامانه‌ی انجام کار</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>عنوان کار</th>
                    <th>ارزش کار</th>
                    <th>تخمین زمانی</th>
                    <th>صاحب کار</th>
                    <th>توضیحات</th>
                </tr>
                </thead>
                <tbody>
                {% for task in page_obj %}
                    <tr>
                        <td class="table_element">{{ task.title }}</td>
                        <td class="table_element">{{ task.value|stringformat:'i تومان' }}</td>
                        <td class="table_element">{{ task.timeEstimation }}</td>
                        <td class="table_element">{{ task.employer }}</td>
                        <td class="table_element"><a href="{% url 'work_system:task_detail' task.id %}">detail</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div id="tasks-paginator">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li><a href="?page=1">1</a></li>
                        <li><a href="?page={{ page_obj.previous_page_number }}"> >> </a></li>
                    {% endif %}
                    <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}"> << </a></li>
                        <li>
                            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="col-md-3">
            {% if user.is_authenticated %}
                <h3> شما با نام کاربری {{ user.get_username }} وارد شده‌اید. </h3>
                {% if user.isEmployee %}
                    <form action="{% url 'work_system:create_task' %}" method="get">
                        <button type="submit" class="btn btn-default btn-block">اضافه کردن کار</button>
                    </form>
                {% endif %}
                <form action="{% url 'work_system:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-block">خروج</button>
                </form>
            {% else %}
                <h3> ورود </h3>
                <form action="{% url 'work_system:email_login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label style="width: 100%">
                            <input type="email" class="form-control" name="email" placeholder="ایمیل">
                        </label>
                    </div>
                    <button type="submit" class="btn btn-default btn-block">ورود</button>
                </form>
                <hr/>
                {% if signup_form.non_field_errors %}
                    <h3>{{ signup_form.non_field_errors }}</h3>
                {% else %}
                    <h3>ثبت نام</h3>
                {% endif %}
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ signup_form.username.errors }}
                        <label style="width: 100%">
                            <input name="username" maxlength="100" class="form-control" placeholder="نام‌کاربری">
                        </label>
                    </div>
                    <div class="form-group">
                        {{ signup_form.email.errors }}
                        <label style="width: 100%">
                            <input name="email" class="form-control" placeholder="ایمیل" type="email">
                        </label>
                    </div>
                    <div class="form-group">
                        {{ signup_form.password.errors }}
                        <label style="width: 100%">
                            <input name="password" class="form-control" placeholder="رمزعبور" type="password">
                        </label>
                    </div>
                    <div class="form-group">
                        {{ signup_form.password_rpt.errors }}
                        <label style="width: 100%">
                            <input name="password_rpt" class="form-control" placeholder="تکرار رمز عبور"
                                   type="password">
                        </label>
                    </div>
                    <div class="form-group">
                        {{ signup_form.isEmployee.errors }}
                        <label><input name="isEmployee" type="checkbox">کارفرما</label>
                    </div>
                    <button class="btn btn-default btn-block">ثبت نام</button>
                </form>
            {% endif %}
        </div>
    </div>
    <footer>
        <hr/>
        <span> درباه‌ی ما</span>
        <span>قوانین</span>
    </footer>
</div>
</body>
</html>

django/work_system/templates/new_task.html
<!DOCTYPE html>
<html lang="fa">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'work_system/main.css' %}">
    {#    <link rel="stylesheet" href="../static/work_system/main.css">#}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>new task</title>

</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div id="main-content" class="col-md-9">
            <h1> سامانه‌ی انجام کار</h1>
            <div>
                <h3> افزودن کار جدید </h3>
                {% if form.non_field_errors %}
                    <h3>{{ form.non_field_errors }}</h3>
                {% endif %}
                <form action="{% url 'work_system:create_task' %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        {{ form.title.errors }}
                        <div class="col-sm-6">
                            <input name="title" class="form-control" maxlength="250">
                        </div>
                        <label class="control-label col-sm-2" for="title">عنوان</label>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        {{ form.description.errors }}
                        <div class="col-sm-6">
                            <textarea name="description" class="form-control" cols="40" rows="10"></textarea>
                        </div>
                        <label class="control-label col-sm-2" for="title">توضیحات</label>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        {{ form.value.errors }}
                        <div class="col-sm-6">
                            <input name="value" class="form-control" type="number">
                        </div>
                        <label class="control-label col-sm-2" for="title">قیمت</label>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        {{ form.timeEstimationDay.errors }}
                        <div class="col-sm-6">
                            <input name="timeEstimationDay" class="form-control" type="number">
                        </div>
                        <label class="control-label col-sm-2" for="title">روز زمان تخمینی</label>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        {{ form.timeEstimationHour.errors }}
                        <div class="col-sm-6">
                            <input name="timeEstimationHour" class="form-control" type="number">
                        </div>
                        <label class="control-label col-sm-2" for="title">ساعت زمان تخمینی</label>
                    </div>
                    <div class="col-sm-4"></div>
                    <div class="col-sm-8">
                        <button class="btn btn-default btn-block">افزودن کار</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-3">
            {% if user.is_authenticated %}
                <h5> شما با نام کاربری {{ user.get_username }} وارد شده‌اید. </h5>
                <a class="btn btn-default btn-block" href="{% url 'work_system:home' %}">صفحه‌ی اصلی</a>
                <a class="btn btn-default btn-block" href="{% url 'work_system:logout' %}">خروج</a>
            {% else %}
                <a class="btn btn-default btn-block" href="{% url 'work_system:home' %}">صفحه‌ی اصلی</a>
            {% endif %}
        </div>
    </div>
    <footer>
        <hr/>
        <span> درباه‌ی ما</span>
        <span>قوانین</span>
    </footer>
</div>
</body>
</html>

django/work_system/templates/no_permission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>message</title>
</head>
<body>
<div style="
width: 100%;
text-align: center;
padding-top: 200px;
font-size: large;
"
dir="rtl">
    شما دسترسی لازم برای باز کردن این صفحه را ندارید.
</div>
<div style="
width: 100%;
padding-top: 15px;
text-align: center;
font-size: large;
"
dir="rtl">
    <a href="{% url 'work_system:home' %}">
        صفحه‌ی اصلی
    </a>
</div>
</body>
</html>

django/work_system/templates/send_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>message</title>
</head>
<body>
<div style="
width: 100%;
text-align: center;
padding-top: 200px;
font-size: large;
"
dir="rtl">
    لینک لاگین به ایمیل شما به آدرس {{ email }} ارسال شد.
</div>
<div style="
width: 100%;
padding-top: 15px;
text-align: center;
font-size: large;
"
dir="rtl">
    <a href="{% url 'work_system:home' %}">
        صفحه‌ی اصلی
    </a>
</div>
</body>
</html>

django/work_system/templates/task_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>message</title>
</head>
<body>
<div style="
width: 100%;
text-align: center;
padding-top: 200px;
font-size: large;
"
dir="rtl">
    کار مورد نظر موفقیت رزرو شد.
</div>
<div style="
width: 100%;
padding-top: 15px;
text-align: center;
font-size: large;
"
dir="rtl">
    <a href="{% url 'work_system:home' %}">
        صفحه‌ی اصلی
    </a>
</div>
</body>
</html>

django/work_system/templates/task_full.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>message</title>
</head>
<body>
<div style="
width: 100%;
text-align: center;
padding-top: 200px;
font-size: large;
"
dir="rtl">
    کار شما توسط شخص دیگری رزرو شده است.
</div>
<div style="
width: 100%;
padding-top: 15px;
text-align: center;
font-size: large;
"
dir="rtl">
    <a href="{% url 'work_system:home' %}">
        صفحه‌ی اصلی
    </a>
</div>
</body>
</html>

django/work_system/templates/task_reserved.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>message</title>
</head>
<body>
<div style="
width: 100%;
text-align: center;
padding-top: 200px;
font-size: large;
"
dir="rtl">
    کار شما با موفقیت رزرو شد.
</div>
<div style="
width: 100%;
padding-top: 15px;
text-align: center;
font-size: large;
"
dir="rtl">
    <a href="{% url 'work_system:home' %}">
        صفحه‌ی اصلی
    </a>
</div>
</body>
</html>